In [35]:
import torch
import numpy as np
import os
import torch.nn as nn

In [2]:
# Torch tensors
# Defining a one dimensional tensor
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [3]:
# Defining a two dimensional tensor
b = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(b)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [4]:
# The size of the tensors 
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([3, 3])
torch.Size([3])
torch.Size([3, 3])


In [5]:
#  Getting the Height/rows in b
print(b.shape[0])

3


In [6]:
# Defining different datatypes of tensors
# Float
flo = torch.tensor([[1,2],[3,4]], dtype=torch.float)
doub = torch.tensor([1,2], dtype=torch.double)

In [7]:
# Getting the datatypes for the tensors
print(flo.dtype)
print(doub.dtype)

torch.float32
torch.float64


In [8]:
# Fetching the mean and the standard deviation of a tensor
print(flo.mean())
print(flo.std())

tensor(2.5000)
tensor(1.2910)


In [9]:
# Reshaping the tensors
# If one of the given dimension is given -1 then the size can be inferred which means if for 
# it is given -1,3 then python will find our which nos of other dimensions are required is to satisfy x,-3
# Pytorch will find out the x

print(b.view(-1,1))
print(b.view(9))

# Assigning b a new shape
b = b.view(1,-1)
print("\n Tensor B after assigning new shape {}".format(b))
print("\n The shape of tensor B is {}".format(b.shape))

# Creating a 3D tensor with 2 channels 3 rows and 2 columns
thre_dm = torch.randn(2,3,4)
print(thre_dm)
print(thre_dm.view(2,12))
print(thre_dm.view(2,-1))

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

 Tensor B after assigning new shape tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

 The shape of tensor B is torch.Size([1, 9])
tensor([[[ 0.0053, -0.1609, -0.4107, -0.5862],
         [-0.5446,  0.2137, -0.8196,  1.3846],
         [-0.5664,  0.2875, -0.8852, -1.4499]],

        [[ 1.8488, -0.2969,  0.9424, -0.4392],
         [-1.0954, -0.4682, -0.9525, -0.8017],
         [ 1.6451,  0.3325,  1.2691, -1.1603]]])
tensor([[ 0.0053, -0.1609, -0.4107, -0.5862, -0.5446,  0.2137, -0.8196,  1.3846,
         -0.5664,  0.2875, -0.8852, -1.4499],
        [ 1.8488, -0.2969,  0.9424, -0.4392, -1.0954, -0.4682, -0.9525, -0.8017,
          1.6451,  0.3325,  1.2691, -1.1603]])
tensor([[ 0.0053, -0.1609, -0.4107, -0.5862, -0.5446,  0.2137, -0.8196,  1.3846,
         -0.5664,  0.2875, -0.8852, -1.4499],
        [ 1.8488, -0.2969,  0.9424, -0.4392, -1.0954, -0.

In [10]:
# Creating a matrix with random nos in a range of 0 and 1
rand = torch.rand(4,4)
print(rand)

tensor([[0.8375, 0.2254, 0.5141, 0.5167],
        [0.5352, 0.8949, 0.0142, 0.4650],
        [0.4123, 0.3908, 0.2343, 0.3667],
        [0.7334, 0.9764, 0.2845, 0.0535]])


In [11]:
# Creating a matrix with random nos taken from a normal distribution with mean 0 and variance 1
rand = torch.randn(4,4)
print(rand)
print(rand.dtype)

tensor([[ 0.0976,  0.4659,  0.8670, -0.2110],
        [-1.5707, -0.6930, -0.8440,  2.0431],
        [ 0.4148,  0.6165, -0.6185, -0.8482],
        [-0.8679, -0.0985, -1.2651, -0.6342]])
torch.float32


In [12]:
# Creating a array of 5 random integers from values between 6 and 9 exclusive of 10
in_arr = torch.randint(6,10, (5,))
print(in_arr)
print(in_arr.dtype)

tensor([8, 8, 9, 7, 9])
torch.int64


In [13]:
# Creating a 2d array or matrix of size 3x3 filled with random integers from values between 6 and 9
in_arr = torch.randint(6,10, (3,3))
print(in_arr)
print(in_arr.dtype)

tensor([[8, 7, 7],
        [9, 8, 7],
        [9, 8, 6]])
torch.int64


In [14]:
# Fetching the nos of the elements in the above matrix
print(torch.numel(in_arr))

9


In [15]:
# Creating a 3x3 matrix of zeros of dtype long
z = torch.zeros(3,3, dtype=torch.long)
print(z)
# Creating a 3x3 matrix of ones
x = torch.ones(3,3)
print(x)
print(x.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [16]:
# Converting the tensors data type
xlike = torch.randn_like(x, dtype=torch.double)
print(xlike)

# Adding two tensors 
summation = torch.add(x,xlike)
print(summation)

# Inplace summation
x.add_(xlike)

tensor([[ 1.5560,  0.0656, -0.5199],
        [ 0.0582,  0.1887, -0.0847],
        [ 0.6055, -0.1418, -0.0297]], dtype=torch.float64)
tensor([[2.5560, 1.0656, 0.4801],
        [1.0582, 1.1887, 0.9153],
        [1.6055, 0.8582, 0.9703]], dtype=torch.float64)


tensor([[2.5560, 1.0656, 0.4801],
        [1.0582, 1.1887, 0.9153],
        [1.6055, 0.8582, 0.9703]])

In [17]:
# Slicing tensors
print(x[:-1])
print(x[:,:2])
u = x[:,:2]
print(u)
u = x[2,1]
print(u.item())
print(x[2,:])

tensor([[2.5560, 1.0656, 0.4801],
        [1.0582, 1.1887, 0.9153]])
tensor([[2.5560, 1.0656],
        [1.0582, 1.1887],
        [1.6055, 0.8582]])
tensor([[2.5560, 1.0656],
        [1.0582, 1.1887],
        [1.6055, 0.8582]])
0.8581721782684326
tensor([1.6055, 0.8582, 0.9703])


In [18]:
# Converting a torch tensor to a numpy array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
a.add_(1)
# Here we can notice as soon as we perform any operation in the torch tensor, then numpy array also gets affected
# This is called the numpy bridge
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [19]:
# Converting a numnpy array to a torch tensor
# Same thing we will also have a numpy bridge here
a = np.ones(2)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2.]
tensor([2., 2.], dtype=torch.float64)


In [20]:
# Moving the tensors to cuda

x = x.cuda()
os.system('CUDA_LAUNCH_BLOCKING=1')
print(x)

tensor([[2.5560, 1.0656, 0.4801],
        [1.0582, 1.1887, 0.9153],
        [1.6055, 0.8582, 0.9703]], device='cuda:0')


In [23]:
if torch.cuda.is_available():
    add_sum = b.cuda()
    print(add_sum)

tensor([2., 2.], device='cuda:0', dtype=torch.float64)


In [24]:
# Converting a list to a tensor
ls = [2,3,4,5,6]
to_ls = torch.tensor(ls)
print(to_ls, to_ls.dtype)

tensor([2, 3, 4, 5, 6]) torch.int64


In [28]:
# Concatenating tensors
f1 = torch.randn(2,5)
t2 = torch.randn(3,5)
# Concatenating along rows
con1 = torch.cat([f1, t2])
print(con1)
f2 = torch.randn(2,3)
print(f2)
f3 = torch.randn(2,5)
print(f3)
# Concatenating along 1 dim [columns]
con3 = torch.cat([f2,f3], 1)
print(con3)

tensor([[-0.3153,  1.2857, -1.5175,  0.1393, -0.0069],
        [-1.0783,  0.2786, -0.5890, -0.5115, -0.8723],
        [-1.1117, -0.2263, -1.4117, -1.0286, -0.2465],
        [ 2.1026, -0.3923, -0.8967,  1.1783, -0.4872],
        [ 0.5793, -0.4394, -0.7675, -1.0861, -0.3882]])
tensor([[-0.9926, -0.7145,  0.4150],
        [-0.5243,  0.8682, -0.7619]])
tensor([[ 0.9485,  0.9568, -0.7950, -0.8767,  0.1593],
        [-1.1366, -2.0665,  2.3545, -0.5904,  0.2500]])
tensor([[-0.9926, -0.7145,  0.4150,  0.9485,  0.9568, -0.7950, -0.8767,  0.1593],
        [-0.5243,  0.8682, -0.7619, -1.1366, -2.0665,  2.3545, -0.5904,  0.2500]])


In [31]:
# Adding dimensions to the tensors
ten1 = torch.tensor([1,2,3,4,5])
ten2 = torch.unsqueeze(ten1, 0)
print(ten2)
print(ten2.shape)
ten3 = torch.unsqueeze(ten1, 1)
print(ten3)
print(ten3.shape)
ten4 = torch.randn(2,3,4)
print(ten4)
tenc = ten4[:,:,2]
print(tenc)
print(tenc.shape)
tend = torch.unsqueeze(tenc, 2)
print(tend)
print(tend.shape)

tensor([[1, 2, 3, 4, 5]])
torch.Size([1, 5])
tensor([[1],
        [2],
        [3],
        [4],
        [5]])
torch.Size([5, 1])
tensor([[[-0.2771,  0.5967,  0.3682,  0.6202],
         [-1.0894,  0.1918,  1.4574,  0.2619],
         [ 0.2236,  1.9963, -0.6731,  0.7798]],

        [[-0.7252,  0.1376,  1.9654,  0.0042],
         [-0.0485, -0.4292, -0.0868, -0.6094],
         [ 0.0996, -0.5149, -0.3623, -0.3933]]])
tensor([[ 0.3682,  1.4574, -0.6731],
        [ 1.9654, -0.0868, -0.3623]])
torch.Size([2, 3])
tensor([[[ 0.3682],
         [ 1.4574],
         [-0.6731]],

        [[ 1.9654],
         [-0.0868],
         [-0.3623]]])
torch.Size([2, 3, 1])


In [32]:
# Autograd

#  If autograd is set to true , then pytorch keeps track of the gradient 
x = torch.tensor([1., 2., 3], requires_grad=True)
y = torch.tensor([4., 5., 6], requires_grad=True)

# Computing the gradient
z = x+y
print(z)
print(z.grad_fn)
# If we keep on continuing
s = z.sum()
print(s)
print(s.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)
tensor(21., grad_fn=<SumBackward0>)


In [33]:
# Lets backpropagate on s , we can fing the gradients of s with respect to x
s.backward()
print(x.grad)

tensor([1., 1., 1.])


In [34]:
# Default is requires_grad = false
x = torch.randn(2,2)
y = torch.randn(2,2)
print(x.requires_grad, y.requires_grad)
z = x+y
# Thus we cant back prop
print(z.grad_fn)
# Another way of setting require grad to true
x.requires_grad_()
y.requires_grad_()
z = x+y
print(z.grad_fn)
print(z.requires_grad)

# Z has the computation history that can relate to x and y
new_z = z.detach()
print(new_z.grad_fn)
# z.detach returns a tensor that shares the same storage as 'z' but with the computation history forgotten. 
# It doesnt know anything about how it was computed. In other words its tensor that has broken away from its past history

# Stopping tensors to stop tracking history
print(x.requires_grad)
print((x+10).requires_grad)

with torch.no_grad():
    print((x+10).requires_grad)

False False
None
True
None
True
True
False


In [36]:
# Loss functions
pred = torch.randn(4,5)
label = torch.randn(4,5)

In [37]:
# MSE
mse = nn.MSELoss(reduction='none')

In [38]:
loss = mse(pred, label)
loss

tensor([[7.8519e-01, 2.1675e-01, 9.2598e-03, 2.5043e-02, 1.6445e+00],
        [1.1061e-01, 4.8832e-01, 1.7214e-01, 8.4170e-03, 1.1453e-06],
        [2.5069e+01, 1.5267e+00, 6.1410e-02, 3.6202e-01, 1.9199e+00],
        [6.7003e-03, 4.4402e-01, 1.8229e+01, 4.8144e+00, 1.2807e-02]])

In [39]:
# mean reduction stands for the mean of all the above elemenets
mse = nn.MSELoss(reduction='mean')
loss= mse(pred, label)
loss

tensor(2.7953)

In [40]:
# sum reduction stands for the sum of all the above elements
mse = nn.MSELoss(reduction='sum')
loss=mse(pred, label)
loss

tensor(55.9055)

In [42]:
# scratch implementation of mse
mse = ((pred-label)**2).mean()
mse

tensor(2.7953)

In [44]:
mse = ((pred-label)**2).sum()
mse

tensor(55.9055)

In [45]:
# Binary cross entropy 
label = torch.zeros(4,5).random_(0,2)
label

tensor([[1., 0., 1., 0., 0.],
        [1., 1., 0., 1., 0.],
        [0., 0., 1., 1., 1.],
        [0., 1., 0., 0., 0.]])

In [46]:
sg = nn.Sigmoid()
bce = nn.BCELoss(reduction='mean')
bce(sg(pred), label)

tensor(0.7571)

In [48]:
# BCE with logit loss
bce = nn.BCEWithLogitsLoss(reduction='mean')
bce(pred, label)

tensor(0.7571)

In [52]:
# sigmoid implementation
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [54]:
# scratch implemetation
prednum = pred.numpy()
lalnum = label.numpy()

prednum = sigmoid(prednum)

lossval = []
for idx in range(len(lalnum)):
    batchls = []
    for idj in range(len(lalnum[0])):
# if 1 then -log(x) or else -log(1-x)
        batchls.append(-np.log(prednum[idx][idj]) if lalnum[idx][idj] == 1 else -np.log(1-prednum[idx][idj]))
    lossval.append(batchls)
print(np.mean(lossval))

0.7571293923188918


In [58]:
#  Weight initialization
layer = nn.Linear(5,5)
layer.weight.data

tensor([[ 0.0338,  0.4319, -0.0487,  0.1131, -0.4337],
        [ 0.0342,  0.3774, -0.3434, -0.3009,  0.0387],
        [ 0.3433,  0.3227,  0.2714, -0.1950, -0.1475],
        [-0.3630, -0.2725, -0.0703, -0.4428,  0.1671],
        [ 0.1390,  0.3801, -0.1262,  0.1728, -0.1119]])

In [59]:
# uniform initialisation
nn.init.uniform_(layer.weight.data ,a=0.0, b=3)

tensor([[2.3935, 2.8700, 1.7786, 0.9714, 1.6946],
        [0.6508, 0.9485, 1.1507, 0.7879, 0.5309],
        [0.8455, 2.0859, 1.4195, 2.5097, 1.4688],
        [0.7639, 0.4242, 2.5178, 2.3848, 0.2044],
        [1.7226, 1.5892, 0.8496, 1.6147, 2.4992]])

In [62]:
# normal distribution
nn.init.normal_(layer.weight.data, mean=0.0, std=1)

tensor([[ 0.8364,  2.2816, -1.1516, -0.6965,  1.4944],
        [ 0.8730,  0.0351, -0.6428, -1.1610,  0.6280],
        [-0.2186,  0.4613,  0.7571, -0.2126,  0.2457],
        [ 0.2771, -0.3233, -0.0539,  0.6020,  0.6495],
        [ 1.4403,  0.6352,  0.3383,  0.6251,  1.6101]])

In [63]:
nn.init.normal_(layer.weight.data, mean=0.0, std=.2)

tensor([[-0.0854,  0.0652,  0.2581,  0.2509, -0.2999],
        [ 0.0171,  0.0035,  0.3003, -0.1946,  0.3058],
        [-0.2565,  0.1600,  0.0123, -0.1609,  0.2886],
        [-0.0546, -0.3542, -0.1709,  0.1001,  0.3660],
        [-0.1649, -0.2011, -0.1517, -0.1989,  0.0550]])

In [65]:
# constant initialisation
nn.init.constant_(layer.bias, 0)

Parameter containing:
tensor([0., 0., 0., 0., 0.], requires_grad=True)

In [66]:
nn.init.zeros_(layer.bias)

Parameter containing:
tensor([0., 0., 0., 0., 0.], requires_grad=True)

In [67]:
layer.bias

Parameter containing:
tensor([0., 0., 0., 0., 0.], requires_grad=True)

In [69]:
# xavier initialisation
nn.init.xavier_uniform_(layer.weight.data, gain=1)

tensor([[ 0.7505, -0.2085,  0.7480,  0.6749, -0.6570],
        [ 0.4072, -0.3302, -0.5706, -0.4058,  0.4960],
        [-0.7058,  0.7702, -0.0217,  0.5984, -0.0398],
        [-0.1148, -0.6094,  0.5956,  0.4466,  0.3286],
        [ 0.3436, -0.4977,  0.3766,  0.6729,  0.4752]])

In [70]:
nn.init.xavier_normal_(layer.weight.data, gain=1)

tensor([[-0.1375, -0.2692, -0.7040,  0.6446,  0.3688],
        [ 0.1992,  0.9466, -0.7689, -0.7558, -0.8629],
        [ 0.4228,  0.1924,  0.5441,  0.3148,  0.1434],
        [-0.1396, -0.4639,  0.3071,  0.2512,  0.0898],
        [ 0.5552,  1.0036, -0.0120,  0.5545, -0.9677]])